### ISSUE TITLE
[Bug] zos_job_submit do not respect location: LOCAL and fails searching for the job in the target lpar

### ISSUE THREAD

**Issue by billpereira** [ansible-collections/ibm_zos_core#1012]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.1.1

### IBM Enterprise Python

v3.8.x

### IBM z/OS Ansible core Version

v1.6.0

### ansible-version

latest

### z/OS version

v2.5

### Ansible module

zos_job_submit

### Bug description

When using `location: LOCAL`  after moved from ansible core modules from 1.4 to 1.6 i started to see an error unable to submit the jobs...
{"changed": false, "checksum": "252fb2efe9dbb32e6d462d2231aac7dadaf1f618", "dest": "/tmp/ansible.k072sa5o", "duration": 0, "gid": 1, "group": "OMVS", "job_id": 
null, "md5sum": "9944ea3a3d8dec428aacac065774dc0b", "mode": "0600", "msg": "Unable to submit job /u/miscuser/an01s/search_certificates.jcl, the job submission h
as failed. Without the job id, the error can not be determined. Consider using module `zos_job_query` to poll for the job by name or review the system log for p
urged jobs resulting from an abend.", "owner": "USERID", "size": 3707, "src": "/u/miscuser/userid/.ansible/tmp/ansible-tmp-1696517656.8198025-117-187111494265968/
source", "state": "file", "stderr": "", "stderr_lines": [], "uid": 5262645}

**Comment by ddimatos** [comment]
@billpereira - IBM z/OS Core version 1.6.0 has [minimal ZOAU and Python requirements](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html#id5) not met according to what has been selected for this issue. 

Requirements shared in the document link for v1.6.0 are:

> Supported by [z/OS®](https://www.ibm.com/docs/en/zos) V2R4 or later
> Supported by the [z/OS® shell](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.4.0/com.ibm.zos.v2r4.bpxa400/part1.htm)
> Supported by [IBM Open Enterprise SDK for Python](https://www.ibm.com/products/open-enterprise-python-zos) [3.9](https://www.ibm.com/docs/en/python-zos/3.9) - [3.11](https://www.ibm.com/docs/en/python-zos/3.11)
> Supported by IBM [Z Open Automation Utilities 1.2.2](https://www.ibm.com/docs/en/zoau/1.2.x) (or later) but prior to version 1.3.

**Comment by billpereira** [comment]
Hi Thanks for the feedback, but even using Python 3.11 and Z Open automation Utilities 1.2.5 it still fails. With a different error msg:
TASK [Submit the IDIDMAP Report and get the content back] **********************
fatal: [xat1]: FAILED! => {
    "changed": false
}

MSG:

src and dest are required

-----


bill@XAT:/u/pereirw/ansb/ididmap$ which zoaversion
/u/pereirw/zoau-1.2.5/bin/zoaversion
bill@XAT:/u/pereirw/ansb/ididmap$ zoaversion
2023/09/20 17:20:50 CUT V1.2.5.0 dfc0ed10 3938 PH54246 998 7544c1ea
bill@XAT:/u/pereirw/ansb/ididmap$ which python
/usr/lpp/road4z/bin/python
bill@XAT:/u/pereirw/ansb/ididmap$ python --version
Python 3.11.4

------

            ansible_python_interpreter: /usr/lpp/road4z/bin/python
            environment_vars:
               PYZ: "/usr/lpp/road4z"
               ZOAU: "/u/pereirw/zoau-1.2.5"
               _BPXK_AUTOCVT: "ON"
               ZOAU_HOME: "{{ ZOAU }}"
               PYTHONPATH: "{{ ZOAU }}/lib"
               LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
               PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"

**Comment by fernandofloresg** [comment]
Hi @billpereira Could you also share the task?

**Comment by ddimatos** [comment]
I would add to @fernandofloresg ask to include the verbose output (narrow it down to this task only) , the full environment  vars because what you shared are partial, see [here](https://github.com/ansible-collections/ibm_zos_core/discussions/657) for an example of those env vars or here for more [details](https://github.com/IBM/z_ansible_collections_samples/blob/main/docs/share/zos_core/configuration_guide.md#group-variables).

To ensure successful triaging and use of everyones time, we need a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example), basically in everything you can.

**Comment by billpereira** [comment]
Its failing submitting any JCL from local, while using zos_core 1.4 in production it works just fine. I need to move for 1.6 cause i need to use some new features from the newer modules, i have python and ZOAU in place in newer version in my test environment with the 1.6 as i pasted before, but once i try with 1.6 i start getting errors with job submit.

---
Playbook
---
- name: Getting information from TSO USERDID
  hosts: sys11
  gather_facts: false
  vars: 
    search_cn: "******l*"
    # cn: "******"
    ididmap_user: ******
    dn: "CN=*******,O=...t,C=NL"
    sysplex: "XAT"
  environment: "{{ environment_vars }}"
  tasks:
    # Prepare template for IDIDMAP REPORT
    - name: "Prepare JOB for generate IDIDMAP REPORT"
      ansible.builtin.template:
        src: "./ididmap_report.j2"
        dest: "./ididmap_report.jcl"
      delegate_to: localhost


    - name: Reading content of my new "./ididmap_report.jcl"
      ansible.builtin.set_fact:
        jcl_idid: "{{ lookup('file','./ididmap_report.jcl') }}"
      delegate_to: localhost 
    
    - name: Submit IDIDMAP Report JOB.
      ibm.ibm_zos_core.zos_job_submit:
        src: "./ididmap_report.jcl"
        location: LOCAL
        return_output: true
      register: ididmap_report_output 

        
    - name: Search for CKREPORT on the IDIDMAP Report Job
      ansible.builtin.set_fact:
        ckreport_list: "{{item | join('\n')}}"
      loop: "{{ididmap_report_output['jobs'][0] | json_query(report_query)}}"
      vars:
        report_query: "ddnames[?ddname=='CKREPORT'].content"

    - name: Save report to provide input for scripts/ididmap_report.py
      ansible.builtin.copy:
        content: "{{ ckreport_list }}"
        dest: ididmap_report.output
      delegate_to: localhost

    - name: Running python script to get the report entries
      shell: python3 ./ididmap_report.py 
      delegate_to: localhost 
      register: ididmap_report_stdout

    - name: Getting variable from script
      ansible.builtin.set_fact:
        ididmap_report_results: "{{ididmap_report_stdout.stdout | from_json }}"

    - debug:
        var: ididmap_report_results 

----
Inventory
----

all:
   children:
      zos_hosts:
         children:
            zos_test_hosts:
               hosts:
                  sys1:
                     ansible_host: ***********
         vars:
            PYZ: "/usr/lpp/road4z"
            ZOAU: "/usr/local/zoau"
            ansible_python_interpreter: /usr/lpp/road4z/bin/python
            environment_vars:
               PYZ: "/usr/lpp/road4z"
               ZOAU: "/u/pereirw/zoau-1.2.5"
               _BPXK_AUTOCVT: "ON"
               ZOAU_HOME: "{{ ZOAU }}"
               PYTHONPATH: "{{ ZOAU }}/lib"
               LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
               PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
               _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
               _TAG_REDIR_ERR: "txt"
               _TAG_REDIR_IN: "txt"
               _TAG_REDIR_OUT: "txt"
               _CC_LIB_PREFIX: "SYS1"
               LANG: "C"

**Comment by ddimatos** [comment]
@billpereira

1. Are you setting [pipelining](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-pipelining) to true so we can properly try a recreate?
2. When you get a chance, please share the verbose output using `-vvvv` so we may see the full traceback
3. When you set_fact and perform a lookup`jcl_idid: `jcl_idid: "{{ lookup('file','./ididmap_report.jcl') }}"` , can you please verify the content is there and perform a debug
4. I know this is obvious but want to not overlook anything, is the JCL created by your `template` task leaving the file in a readable state by the playbook user? 
5. Can you try submitting the JCL with an absolute path instead of the local path? 

```
    - name: Reading content of my new "./ididmap_report.jcl"
       ansible.builtin.set_fact:
         jcl_idid: "{{ lookup('file','./ididmap_report.jcl') }}"
      delegate_to: localhost 
   - name: Print file contents
     ansible.builtin.debug:
        msg: "The content of file is {{ jcl_idid }}"
```
Note, that the initial env vars you shared were truncated, we ask for complete content so we can recreate correctly 

@fernandofloresg 
1. I would try this recreate, not necessarily the entire playbook but specifically the relative `./some/file` LOCAL path as I do not see a relative test , I see many absolute test LOCAL test cases. 
2. This [code snippet ](https://github.com/ansible-collections/ibm_zos_core/blob/bdf9168d35466060305f1eeecaa673382e88f543/plugins/action/zos_job_submit.py#L46)is there from the original commit 3 yrs ago, unfortunately the message is not a good message because `zos_job_submit` does not ever expect a `dest` (destination) , for some reason our plugin is not seeing the file. I know we have plans to rewrite this plugin but I would consider the incorrect msg a bug (be it a minor bug).

**Comment by fernandofloresg** [comment]
I tried to recreate this issue and: 
1. zos_job_submit module works fine with local relative paths.
2. We do need to enahance error messages for this purpose I created issue #1050

**Comment by ddimatos** [comment]
@billpereira - Hi Bill, above on Oct 31st we requested additional information, if this is still an issue please update the issue else by our next Triage on Dec 14th 2023, this issue will be closed. We generally allow 30 days for issues to remain without activity, we are nearing 45 by our next Triage and did so to honor  how the holidays impact our users. Thank you.

**Comment by richp405** [comment]
Time period has passed.
