### ISSUE TITLE
[Enabler] Add test to show that zos_job_submit obeys return_output correctly

### ISSUE THREAD

**Issue by richp405** [ansible-collections/ibm_zos_core#1061]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_job_submit

### Enabler description

PR #1058 extension (previous issue #1041)

It was determined that zos_job_submit was querying and then blanking out dd segments on a job, leading to unnecessary access to information.  We changed the query to no longer request the dd information if "return_output" was set to false. 

We need to add a unit test that can verify that job details are not being requested by job_output when return_output (dd_scan) is set to false.  The challenge will be in seeing a value that is not explicitly returned.

**Comment by richp405** [comment]
After a few discussions, it was determined that more harm than good would come out of 'reaching in' to see if an extra call was being made.  This was verified by doing debug testing and log testing, which are not appropriate for unit testing modules.

**Comment by ddimatos** [comment]
There is a test case today that validates if the response is omitted when `return_output` is set to `false` , the issue is that it was simply omitted in the past but still performed a query impacting performance, thus I agree that no further testing should be done that would fall outside general testing meaning having to dig into logs, custom options just to evaluate of a query was performed, this falls into profiling not functional testing.
