### ISSUE TITLE
[Module] Investigate new module - Easy service data transfer to IBM using PDUU

### ISSUE THREAD

**Issue by ledina** [ansible-collections/ibm_zos_core#1454]
### Is there an existing issue for this?

- [X] There are no existing issues.

### New module description

CICS customers often use [PDUU](https://www.ibm.com/docs/en/zos/2.4.0?topic=aids-amapdupl-problem-documentation-upload-utility) to transfer large chunks of data sets to IBM to use for problem determination in cases of issues. This would be a great enhancement to the collection as it ensures the data is transferred correctly and it is hassle free for our customers.

### User story

As an Ansible user, I am able to easily transfer large data sets to IBM for problem determination without worrying about how to split the data, compression or the transfer

**Comment by ddimatos** [comment]
@ledina thank you for the module request, we will review it and place our thoughts and notes in this issue.

**Comment by ddimatos** [comment]
The utility [PDUU](https://www.ibm.com/docs/en/zos/2.4.0?topic=aids-amapdupl-problem-documentation-upload-utility) differentiation over other compression options such as `ADRDSSU` `dump` and `restore` is that this utility is designed as a service aid but can be also used in data transport because not only does it compress data, it breaks into chunks and concurrently delivers it to the destination reducing transport times. 

The utility options can be found [here](https://www.ibm.com/docs/en/zos/3.1.0?topic=utility-jcl-statements-pduu), while there are a bit over 40 of them. 

It appears to be a niche ask, so we would want to explore this further with UX to gauge the interest so that if this is to be accepted into the backlog it is appropriately prioritized. 

In reviewing this, here are my initial thoughts and possibly concerns. 
- Is this niche module?
- Is this better suited as an playbook example using module `zos_mvs_raw`
- The JCL samples are not that complicated and align well to `zos_mvs_raw` but the JCL samples don't really take into account the 40+ keywords
- This is going to be starting either a HTTPS or FTP connection to the target, its sort of leverages Ansible without direct integration meaning , the connections Ansible makes are not reused and in some ways not very Ansible friendly by spawning its own connection which means users who specify connection attributes for Ansible will not propagte into this utilities connection.  
- How is FTP viewed in today's security centric world, we can force disablement via our controlled keyword usage so that is not a concern but if we do disable it, is it something users would have wanted which put us possible in a disposition with Ansible, RH and IBM? 
- If we expose many (not all keywords) the investment seems quite large in terms of functional testing over other modules we develop which are not niche modules, which brings me back to my ROI comment above. For example, there are many keywords that can be used to connect to the target system, some of which are using a key ring, keycert, proxy, ciphers, attls, etc, all these will require more system administration and setup for our systems thus equal or greater time to maintain and test the module over the development of the module which makes concerns me for the ongoing cost to maintain what appears to be a niche module. 

While it may appear I am not for the module, that is not my position, I don't see this an overly complicated module to develop, choosing the keywords and mapping those to a mondern interface will be a bit tricky but the concerns I have are more about how valuable this is to the community in relation to ongoing costs to keep this module operational introducing new technical debt we will need to continue to carry.

**Comment by ddimatos** [comment]
From what we collected, folks did believe this could be useful if the playbook tasks would simplify the PDUU usage meaning the data that is transmitted with PDUU could be Ansible tasks that will prepare the data for transmission. 

Additional feed back was if this could replace the traditional workflow, where (below) is minimized.
  terse --> upload --> unterse workflow 

I will transfer this issue over to the [z_ansible_collections_samples](https://github.com/IBM/z_ansible_collections_samples) community to be assigned and tracked there for development.

**Comment by ddimatos** [comment]
I have moved this issue over to the [samples repository](https://github.com/IBM/z_ansible_collections_samples/issues/292) so that someone there can review the request.
