### ISSUE TITLE
[Bug][zos_job_output] ValueError('Invalid argument \"@02858\" for type \"qualifier_pattern\".')

### ISSUE THREAD

**Issue by gngrossi** [ansible-collections/ibm_zos_core#1486]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Bug description

Tried running this task but returned an error for the owner.
owner: "@02858"

  - name: Get output
    zos_job_output:
      job_name: "*"
      job_id:   "J*"
      ddname:   "?"
      owner:    "{{ansible_user}}"

--

TASK [Get output] ***************************************************************************************************************
fatal: [mvs-sysd]: FAILED! => {"changed": false, "msg": "ValueError('Invalid argument \"@02858\" for type \"qualifier_pattern\".')"}

### IBM z/OS Ansible core Version

v1.9.0

### IBM Z Open Automation Utilities

v1.2.5 (default)

### IBM Enterprise Python

v3.11.x (default)

### ansible-version

v2.16.x (default)

### z/OS version

v2.5 (default)

### Ansible module

zos_job_output

### Playbook verbosity output.

Ran this task returning the output snippet.
  - name: Get output
    zos_job_output:
      job_id: "{{JOBID}}"
      ddname: "{{JOBLG}}"
    register: job_out2
--
                    "job_id": "J0020333",
                    "job_name": "@02858CZ",
                    "owner": "@02858",
--
Tried running this task but returned an error for the owner.
  - name: Get output
    zos_job_output:
      job_name: "*"
      job_id:   "J*"
      ddname:   "?"
      owner:    "{{ansible_user}}"

--

TASK [Get output] ***************************************************************************************************************
fatal: [mvs-sysd]: FAILED! => {"changed": false, "msg": "ValueError('Invalid argument \"@02858\" for type \"qualifier_pattern\".')"}

**Comment by fernandofloresg** [comment]
This does seem like a valid user id per [z/OS Security Server RACF Security
Administrator's Guide user naming conventions](https://www.ibm.com/docs/en/zos/2.5.0?topic=users-user-naming-conventions). But the validations in job utils do not adhere to this naming convention see https://github.com/ansible-collections/ibm_zos_core/blob/9503a19090b1f3ea85148b311f37db5d164fadd6/plugins/module_utils/job.py#L94

In my opinion, this should be changed to adhere to the user id naming conventions.

**Comment by gngrossi** [comment]
Thanks for the confirmation. I've been using this RACF user id since 1985  :-)

**Comment by gngrossi** [comment]
Same result with the zos_job_query module

{{ansible_user}} is @02858

  - name: Get output using {{JOBNM}} and {{ansible_user}}
    zos_job_query:
      job_name: "{{JOBNM}}"
      owner:    "{{ansible_user}}"


TASK [Get output using @02858CZ and @02858] ****************************************************************************************
fatal: [mvs-sysd]: FAILED! => {"changed": false, "message": "", "msg": "Invalid argument \"@02858\" for type \"qualifier_pattern\"."}

**Comment by richp405** [comment]
We'll put this in plan for next quarter.

**Comment by gngrossi** [comment]
For planning purposes, is next quarter by 6/30 or 9/30? The reason I ask is that all of our RACF colleague userids are "@..."
thanks...much appreciated

**Comment by gngrossi** [comment]
Still an issue with ibm.ibm_zos_core:==1.10.0-beta.1 and zoau 1311 and python 3.12.1

**Comment by ddimatos** [comment]
@gngrossi - a response is warranted, next quarter is Q3, you should be able to see the issues details on the right plan that contains our planning details, so the work done in Q3 is released at the start of Q4, that would be version version 1.12.0-beta.1. 
<img width="306" alt="image" src="https://github.com/user-attachments/assets/954530d0-9613-4d50-bd04-e3489be4c82c">

**Comment by ddimatos** [comment]
Hello @gngrossi , thank you for bringing this up; allow me to share some thoughts.

This issue is important to us as well, **this is how it got into next quarters plan**, and this is where I would like to take a moment and share our operational processes with the community. 

We triage weekly, we allocate time from our plan to manage that, which means all community issues are evaluated so that the team can decide on the severity. **While we would like nothing more than to address all community issues,** the reality is that we have many users (hundreds) on S&S (entitlement) and those cases have an SLA which can take priority over any community issue. 

In the past, we have triaged quite a few community issues into the backlog, this issue went into next quarter, thus it got a higher priority, even though there exists 2 work arounds for a bug that has existed for nearly 5 years and only been reported once:
1) run with a different user
2) patch, build and install the fix shared [here](https://github.com/ansible-collections/ibm_zos_core/issues/1486#issuecomment-2080188010). 

If options 1 or 2 are not possible, one can monitor the issue and when its complete can easily build from the `dev` branch if they want the changee sooner than a early Q4 release, we generally release in the first 2 weeks of Q4, this is so all the Q3 work can come to closure. 

Let me know if there is more I can share.

**Comment by gngrossi** [comment]
@ddimatos Hello Demetri, Thanks for the comprehensive response…much appreciated. I understand the challenges ahead of you and your team. I am currently testing the technology stack which is a moving target as you know. My aim is to validate the functionality/quality of the software before we commit spending sufficient time and money. We do subscribe to RH AAP, but I understand it will cost additional $ to manage the Z platform. For us, Python 3.12.x, ZOAU 1.3.x and z/OS 3.x with Open Enterprise Foundation are now at point where we can start the automation journey. The z/OS related collections and the Ansible stack itself are now our focus. As far as timing, we can wait for delivery. Thanks again.

**Comment by gngrossi** [comment]
TASK [Get output using @02858CZ and @02858] ****************************************************************************************
fatal: [mvs-sysa.hewitt.com]: FAILED! => {"changed": false, "message": "", "msg": "Invalid argument \"@02858\" for type \"qualifier_pattern\"."}

--

ansible [core 2.16.6]
ibm.ibm_zos_core 1.11.0-beta.1

running on z/OS 3.1

[SYSA] bash-5.2$ python --version
Python 3.12.3
[SYSA] bash-5.2$ which python
/usr/lpp/IBM/cyp/v3r12/pyz/bin/python

[SYSA] bash-5.2$ zoaversion
2024/06/13 14:07:12 CUT v1.3.2.0 edc928b5 5828 PH60438 1232 4da79630
[SYSA] bash-5.2$ which zoaversion
/usr/lpp/IBM/zoau/v1r3/bin/zoaversion

**Comment by gngrossi** [comment]
Hello @fernandofloresg Sorry I missed that 1.11.0-beta.1 wasn't included. I will wait for the .12.0-beta and try again.
thanks
