### ISSUE TITLE
[Enabler] [pipeline] Current default pipelines are running slimbuster 3.9 which is only valid through ansible-core 2.15.x 

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1503]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

On the controller, the last version to support python 3.9 is ansible-core 2.15, with the progression to upcoming ansible-core 2.6, this version of Python must be incremented. The Jenkins source has other slimbusters defined, it should not be a timely change.

![image](https://github.com/ansible-collections/ibm_zos_core/assets/25803172/481e12b8-04be-440b-bf47-728bba6e78a3)

Pipeline log is showing:
```
# ----------------- Docker Image for Testing Environment --------------------- #
FROM python:3.9-slim-buster
WORKDIR /usr/src/app
```

Is it worth investing in a dynamic option to select which of the slimbusters to use, I will leave that up to the team to decide in triage.

**Comment by richp405** [comment]
First pass will connect selected ansible version to slim buster version.  This has been coded, but not yet rolled out.  If needed, we can add the options to the template so the user can select it.

**Comment by richp405** [comment]
![Image](https://github.com/ansible-collections/ibm_zos_core/assets/39140439/d47ce228-552c-46d7-848e-eaaf17153201)

**Comment by richp405** [comment]
2.16 and above now trigger slim buster 3.11.  A major pipeline update including this was rolled out on Jun 4th.

**Comment by richp405** [comment]
I increased the size because other changes got rolled into this: We now support:

- user-controllable version of ansible-lint
- added option for yamllint to check fragment content
- added option for pyflake to check code in both plugins and tests systems
- added more header info to demostrate user choices
- reconfigured fragment test to specifically look for the fragment in either the branch name, or what was provided by the builder
