### ISSUE TITLE
[Enhancement] [zos_operator] Support for specific EMCS console name suffix

### ISSUE THREAD

**Issue by storfibm** [ansible-collections/ibm_zos_core#1792]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enhancement or feature description

Currently, ZOAU's opercmd supports generating specific EMCS consoles with input provided by the user via the "-c" parameter. This functionality should be exploited in zos_operator such that z/OS Core Collection users can drive the same functionality via their Ansible playbooks.

**Acceptance Criteria**
Given zos_operator or zos_operator_action_query
When a playbook needs to invoke opercmd
Then an argument is available to help drive EMCS console name generation with the suffix provided

**Requirements**
-New optional argument in zos_operator or zos_operator_action_query
-Leverage opercmd's -c argument
-Documentation provided with example invocation

**Additional Context**
https://www.ibm.com/docs/en/zoau/1.3.x?topic=commands-opercmd

### Ansible module
zos_operator, zos_operator_action_query

**Comment by ddimatos** [comment]
After evaluating the request, I don't believe there is any benefit to exposing this option to Ansible, for what its worth, there is not even that much value in doing so in ZOAU since version 1.3.2. Allow me to explain.

ZOAU opercmd allows one to control the suffix from 0 - 9999 to avoid any console ID collisions. In other words, if two opercms are run concurrently, by default the same console name is used , this option `-c` will allow the user to create a unique name for each subsequent opercmd invocation avoiding a collision.

In ZOAU 1.3.2, the console name used by default is no longer static, ZOAU will try up to 100 times to find a unique console name by increments of 1, if this were an issue in Ansible, the solution would be to work with ZOAU to change the number of attempts it makes to find a unique console name avoiding the need to have this option available in Ansible. 

My recommendation is this feature not be included in the module.

**Comment by richp405** [comment]
-c option is considered obsolete (commented above by DD)

**Comment by ddimatos** [comment]
Based on the recommendation above, the issue will be closed, feel free to reopen if there is a new use case.
