### ISSUE TITLE
zos_mvs_raw module functionality

### ISSUE THREAD

**Issue by bcronezos** [ansible-collections/ibm_zos_core#307]
Does the zos_mvs_raw module only allow execution of IBM utility programs (IEBGENER,IDCAMS,...etc) or can we execute other non IBM utility programs such as vendor product programs or User programs?  Looking to replace JCL on the mainframe but the documentation is confusing as to what this module actually supports.
Thanks

**Comment by ddimatos** [comment]
@bcronezos - good to hear from you.

**zos_mvs_raw** provides a YAML way to do simple JCL step-like tasks in a playbook rather than pointing to JCL or templating JCL. It leverages ZOAU mvscmd/mvscmdauth, in essence it can run a program that resides in a PDS/PDSE where in our case it was meant to run z/OS programs/utilities (eg IEFBR14, IEBCOPY, IDCAMS, etc) and we have to my knowledge never tested it with a users own or vendor program.

I suppose one could use this for any program (I need to look more into the source to be certain) so long as users correctly map arg values to their programs input, for example with **IKJEFT01** one would use inputs **systsprt** and **systsin** where as with **IDCAMS**  one would use **sysprint** and **stdin**.  

Officially supporting user and vendor programs as I stated is untested to my knowledge thus unsupported. If this is something of significant interest and value to you, feel free to "thumbs up" the ask or have other chime into this issue with use cases so we can prioritize. 

Good question, look forward to hearing more.

**Comment by ddimatos** [comment]
Researching this in more depth if in fact we can run non-ibm utilities

**Comment by ddimatos** [comment]
As [MikeFultonDev](https://github.com/MikeFultonDev) points out, ZOAU mvscmd can run any MVS program, if the MVS program is bound to an APF authorized library be sure to set `zos_mvs_raw` option `auth=true` or in `ZOAU` use `mvscmdauth` where if its bound to a general library, the default  `zos_mvs_raw` option `auth=false` is fine to use or you can use `ZOAU` utility `mvscmd`.

**Comment by ddimatos** [comment]
Answered and related internal ticket 8886 can not be closed.
