### ISSUE TITLE
zos_copy module not working : [Errno 129] EDC5129I No such file or directory and cleanup error

### ISSUE THREAD

**Issue by rchech** [ansible-collections/ibm_zos_core#310]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)

I am trying to run below code 
---
  - name: Copy a local file to a sequential data set
    zos_copy:
    #ibm.ibm_zos_core.zos_copy:
      src: /u/usrerid1/psfile
      dest: USERID1.ANS.COPIED.FROM.UNIX
      ignore_sftp_stderr: yes
      remote_src: yes

Getting below two errors. Please help on this. 

Error1":
{"rc": 129, "msg": "[Errno 129] EDC5129I No such file or directory.: b'mvscmdauth'",
Erro2: 
{"msg": "Error during clean up of file /home/tmp/cics.cprof.socket.home", "stderr": "[Errno 135] EDC5135I Not a directory.: '/HOME/tmp/cics.cprof.socket.home'", "failed": true, "exception": "  File 

{"rc": 129, "msg": "[Errno 129] EDC5129I No such file or directory.: b'mvscmdauth'", "cmd": "mvscmdauth --pgm=IKJEFT01 '--systsprt=*' --systsin=stdin", "failed": true, "exception": "  File \"/tmp/ansible_ibm.ibm_zos_core.zos_copy_payload_a7_q1r1r/ansible_ibm.ibm_zos_core.zos_copy_payload.zip/ansible/module_utils/basic.py\", line 2590, in run_command\n    cmd = subprocess.Popen(args, **kwargs)\n  File \"/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/subprocess.py\", line 956, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/subprocess.py\", line 1826, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\n", "invocation": {"module_args": {"remote_src": true, "is_pds": false, "src_member": false, "local_charset": "UTF-8", "dest": "USERID1.ANS.COPIED.FROM.UNIX", "ignore_sftp_stderr": true, "is_uss": false, "temp_path": null, "src": "/u/userid1/psfile", "copy_member": false, "is_mvs_dest": true}}}

{"msg": "Error during clean up of file /home/tmp/cics.cprof.socket.home", "stderr": "[Errno 135] EDC5135I Not a directory.: '/HOME/tmp/cics.cprof.socket.home'", "failed": true, "exception": "  File \"/tmp/ansible_ibm.ibm_zos_core.zos_copy_payload_a7_q1r1r/ansible_ibm.ibm_zos_core.zos_copy_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_copy.py\", line 1497, in cleanup\n  File \"/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/shutil.py\", line 747, in rmtree\n    return _rmtree_unsafe(path, onerror)\n  File \"/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/shutil.py\", line 606, in _rmtree_unsafe\n    onerror(os.scandir, path, sys.exc_info())\n  File \"/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/shutil.py\", line 603, in _rmtree_unsafe\n    with os.scandir(path) as scandir_it:\n", "invocation": {"module_args": {"remote_src": true, "is_pds": false, "src_member": false, "local_charset": "UTF-8", "dest": "USERID1.ANS.COPIED.FROM.UNIX", "ignore_sftp_stderr": true, "is_uss": false, "temp_path": null, "src": "/u/userid1/psfile", "copy_member": false, "is_mvs_dest": true}}}

**Comment by ddimatos** [comment]
@rchech - I apologize for the delay, the team had been working tirelessly on some long term items. Thank you for the log and bug report. From what I can see I see two issues here:
1) `[Errno 129] EDC5129I No such file or directory.: b'mvscmdauth'"` this error is making me thing ZOAU (Z Open Automation Utilities ) is not configured correctly , please provide me your environment variables used in your playbook. Please note that Ansible does not rely on any `.profile` located on the managed node, all environment variables are configured in the Ansible vars, so your environment vars must be configured correctly else Ansible will not be able to find the ZOAU `mvscmdauth` utility.

2) `"Error during clean up of file /home/tmp/cics.cprof.socket.home", "stderr": "[Errno 135] EDC5135I Not a directory.: '/HOME/tmp/cics.cprof.socket.home'", "failed": true, "exception": ` my thoughts are that because the module failed (bullet 1) that a clean up routine was executed to ensure the module leaves no files or temp files behind. In this case here, the our module assumed that all temp files were created by this module and ansible user which is not only going to be the case. Many temp files act as state management and live on for a long time, even so, our code should not try to delete all temp files instead only the ones it creates. (this is a known bug we are looking into).

**Comment by ddimatos** [comment]
The second bug  (bullet 2) where files were attempted to be cleaned up has been resolved in `ibm_zos_core` v1.3.3 and will be forward ported to the next 1.4.0-beta.2 and so on. 

[Release notes for 1.3.3](https://github.com/ansible-collections/ibm_zos_core/blob/v1.3.3/docs/source/release_notes.rst#version-133)

As for bullet 1, I would need to see your Ansible project or playbooks environment vars. Given its been nearly 2 months with no more activity, I will close this issue. Please repopen if you would like to continue discussion.
