### ISSUE TITLE
[IBM zOS Core - zos_job_output] - The return code is giving blank in JSON output

### ISSUE THREAD

**Issue by rishijoshi07** [ansible-collections/ibm_zos_core#355]
##### SUMMARY

 ```
The return code is giving blank in JSON output
```

##### COMPONENT NAME

```
ibm.ibm_zos_core
```

##### ANSIBLE VERSION

```
`1.3.5`
```

##### SPECIFY ANSIBLE COLLECTION VERSION
```
`source: "https://galaxy.ansible.com"`
```

##### ENVIRONMENT
```
Z/OS 2.5 and Z/os 2.4
```

##### STEPS TO REPRODUCE

```
-> Execute the YAML file through the AWX as a job template
-> Check the output in JSON format.
```

##### EXPECTED RESULTS
```
The return code should not be blank or null.
It should be as whatever actual we got
```

##### ACTUAL RESULTS
```
It should be as whatever actual we got like
-> "code": 0
->"code": 4,
->"code": 8,
->"code": 12,
```

```
Playbook output: 

PLAY [Update source tree if necessary] *****************************************

TASK [Submit JCL operation succeeded] ************************************************

{
  "msg": {
    "dest": "/tmp/ansible.pczhyn5y",
    "src": "/tmp/ansible-tmp-1658236409.8121083-53-208872471420960/source",
    "md5sum": "0f08bb65633967c1fbaab3057e0f31cc",
    "checksum": "aadf6a935363f219f7d51e27d2bb37a3c20978fd",
    "changed": true,
    "uid": 266,
    "gid": 0,
    "owner": "SYS123",
    "group": "SUDOGRP",
    "mode": "0600",
    "state": "file",
    "size": 848,
    "jobs": [
      {
        "job_id": "JOB08209",
        "job_name": "TESTJOB",
        "subsystem": "SYSA",
        "system": "SYSNAME.1",
        "owner": "SYS123",
        "ret_code": {
          "code": null,
          "msg_code": null,
          "msg_txt": "",
          "msg": "AC"
        },
        "class": "E",
        "content_type": "JTYPE.1",
        "ddnames": [
          {
            "ddname": "JESMSGLG",
            "record_count": "4",
            "id": "2",
            "stepname": "JES2",
            "procstep": "",
            "byte_count": "17",
            "content": [
              "1                   J E S 2  J O B  L O G  --  S Y S T E M  D C U F  --  N O D E  A D A J E S 0 F        ",
              "0 ",
              " 08.14.59 JOB08209 ---- TUESDAY,   19 JUL 2022 ----",
              " 08.14.59 JOB08209  IRR010I  USERID SYS123  IS ASSIGNED TO THIS JOB."
            ]
          },
          {
            "ddname": "JESJCL",
            "record_count": "11",
            "id": "3",
            "stepname": "JES2",
            "procstep": "",
            "byte_count": "555",
            "content": [
              " 08.14.59 JOB08209  ICH70001I SYS123  LAST ACCESS AT 08:14:37 ON TUESDAY, JULY 19, 2022",
              " 08.14.59 JOB08209  $HASP373 TESTJOBSTARTED - INIT 4    - CLASS E        - SYS SYSA",
              " 08.14.59 JOB08209  IEF403I TESTJOB- STARTED - TIME=08.14.59",
              "         1 //TESTJOB JOB REGION=0M,CLASS=E,MSGCLASS=X,                           JOB08209",
              "           //            MSGLEVEL=(1,1),NOTIFY=&SYSUID                                     ",
              "           //**                                                                            ",
              "           IEFC653I SUBSTITUTION JCL - REGION=0M,CLASS=E,MSGCLASS=X,MSGLEVEL=(1,1),NOTIFY=SYS123",
              "         2 //FEATURE  EXEC PGM=GIMSMP                                                      ",
              "         3 //SYSPRINT DD SYSOUT=*                                                          ",
              "         4 //SMPOUT   DD SYSOUT=*                                                          ",
              "         5 //SMPCSI   DD DSN=**I,                            "
            ]
          },
          {
            "ddname": "JESYSMSG",
            "record_count": "0",
            "id": "4",
            "stepname": "JES2",
            "procstep": "",
            "byte_count": ""
          }
        ]
      }
    ],
    "duration": 0,
    "message": {
      "stdout": "Submit JCL operation succeeded."
    },
    "failed": false
  },
  "_ansible_verbose_always": true,
  "_ansible_no_log": false,
  "changed": false
}


```

#### Ansible.cfg

```
[defaults]
forks = 25
remote_tmp = /tmp
# ask_pass       = False
# remote_port    = 22

[ssh_connection]
pipelining = True
```

##### JOB OUTPUT
```
"jobs": [
      {
        "job_id": "JOB08209",
        "job_name": "SMPELIST",
        "subsystem": "DCUF",
        "system": "SYSNAME.1",
        "owner": "SYS1311",
        "ret_code": {
          "code": null,
          "msg_code": null,
          "msg_txt": "",
          "msg": "AC"
        },
```

**Comment by ddimatos** [comment]
Thank you for filling out the bug report completely this is very helpful. I feel like from what I can see that this job has not completed or abended. I see not value for `RC=` in the DD JESMSGLG, eg RC=0000. Normally this is an indication its a started task or a running job.

Some added context around the ret_code block:

- msg - would would be the job error such as: "JCL ERROR" | "ABEND(S|U)xxxx" | "CONV ABEND" | "SEC ERROR" | "SYS FAIL"| CANCELED"| "CC xxxx"

- msg_code - would the string value of the job error reduced down to something more consumable such as "00" ("00" | "04" | "08" | "S0C4"

- msg_txt  - is a place holder for us such that if we can deduce from the msg_code some message that is of value and known to us but does not come from zos or zoau we can inject it here to help users. 
    - "The target is unreachable"
    - "Error code xxxx received, please check yyyy is installed and configured"

-  code - if and only if we can convert msg_code into an integer value we return it otherwise we return None
       - Something like msg_code :"00" can be converted to type int: code : 00
       - Something like msg_code :"ABEND", msg_code :"ABEND(S1234)", msg_code :"CANCELED", can not convert thus return None

**Comment by marlm** [comment]
I am having the same issue

**Comment by ddimatos** [comment]
@marlm - Hi, there is no fix yet because its not completely clear what the issue was. It look like a job has not completed or a started task is being queried, we could spend more time guessing but would rather have a clearer understanding before we look into it. 

>  I feel like from what I can see that this job has not completed or abended. I see no value for RC= in the DD JESMSGLG, eg RC=0000. Normally this is an indication its a started task or a running job.

If you can help clarify we can at least properly documented it and see if its been fixed in future planned releases or can be scheduled.

**Comment by marlm** [comment]
Thank you @ddimatos ! I think I found the issue.
The playbook of the original error posted by @rishijoshi07 was not shared but I think the issue can be solved with "wait=true" parameter since by default the parameter is "false", meaning that it doesn't wait the job to complete to get the output information

**Comment by ddimatos** [comment]
@marlm - thank you, I should have been more specific and suggested `wait_time_s` and `wait` options, but yes that is what I was thinking was happening, the job did not have content (RC) and thus came back empty and a `wait` will help. FYI, keep an eye out for `wait` to be deprecated across various modules, right now its only been deprecated in `zos_operator` version 1.4.0-beta.2 (coming out soon), there really is no reason to have `wait` when we can rely simply on `wait_time_s`; the function remains, the interface gets simplified. 

See git [discussion](https://github.com/ansible-collections/ibm_zos_core/discussions/401) for zos_operator.

I appreciate your response as it validates what I thought, I will leave the issue open a little longer for others to comment else eventually I will close it.

**Comment by ddimatos** [comment]
From the discussion it appears this can be closed given also the original reporter has not engaged further. Please reopen if necessary.
