### ISSUE TITLE
[Enabler] [Python 3.11] Validate the latest collection of ibm_zos_core on this early drop

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#434]
### Enabler description

It would be good if when an early drop of IBM Enterprise Python 3.11 became available that it be included into the super share mount and the multipath or other pipelines be able to run full regression on this early drop. Getting ahead of the curve before we encounter any issues, it should be noted testing should be done with and without pipelining enabled.

**Comment by ketankelkar** [comment]
Early release of IBM Enterprise Python 3.11 has been mounted to super shares (thanks to @richp405 ) and preliminary testing against the ibm_zos_core collection has not uncovered any issues

**Comment by ketankelkar** [comment]
No additional issues were uncovered during testing, there were a number of failing test cases in the functional test suite however each failing test case has been remediated (i.e. the failure was resolved or attributed to a non-ibm-python3.11 issue). 

- zos_apf had failing test cases due to changes in return codes between version of ZOAU.
- zos_copy had failing test cases but the copy functionality was confirmed to be working as expected.
- zos_data_set had failing test cases but a change in pathing in the test_config.yml file resolved these.

The rest of the tests with the exception of zos_operator_action_query test suite all passed. 

@ddimatos will be looking into the zos_operator_action_query test cases to determine the root cause of the failures.
