### ISSUE TITLE
[Module][3][Volume] Ensure functional test cases are authored, integrated and operating in our pipeline

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#435]
### Module description

The volume module is a cross team effort (inner-source) collaboration, ensure that the development team leading the volume module with the assistance of a dedicated developer from ibm_zos_core support them and assist in functional tests.

**Comment by ketankelkar** [comment]
Some unit tests and preliminary functional testing has been set up, but not enough of a chunk of progress has been made to warrant marking this item as 'in progress'. the early version of the unit tests are already on github in the zos_ickdsf_init branch

**Comment by ketankelkar** [comment]
chasing down ideas for integrating into CICD pipeline. functional test suite is complete except for potentially adding a test case to recreate return code in hex if possible to recreate.

**Comment by ketankelkar** [comment]
this task was super delayed due to some investigation into making infrastructure available internally in order to integrate the functional tests into the cicd pipeline. We found a way to do it using existing infrastructure and the volume module functional tests successfully ran in the pipeline earlier today
