### ISSUE TITLE
[Module][1][Volume] Develop and update the modules interface  #435

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#471]
### Enabler description

Currently we have a inner source contribution from another team, the git issue is place to take over that work started [here](https://github.com/ansible-collections/ibm_zos_core/tree/zos_ickdsf_init) and update the interface, ensure it meets and aligns with the current ibm_zos_core collection. 

This includes:
- [x] Module docs are complete
- [x] Module options are using best practices as in sub options when needed
- [x] Module option names align to z/OS options but also take into account ibm_zos_core practices

This is usually step 1 of 3 to complete a module where first we focus on the modules options/interface and doc then move to step 2 developing the logic and source but in this case some of step 2 is done which we will track in another JIRA

**Comment by ketankelkar** [comment]
Lots of work has been done in tweaking the interface and docs to fit the ibm_zos_core collection standards as well as Ansible module best practices. Following is a non-comprehensive list of changes and updates made to the inner sourced source code, i'd expect additional changes to be made to the interface/docs over the development and testing cycles but those changes are unknown as of now and hence will be reflected in those specific development and test items instead of here.

- module was renamed from zos_ickdsf_command to zos_ickdsf_init. 
  - The original design was meant to cover multiple ickdsf commands, however the 'init' is complex enough to merit a stand-alone module
- in support of the above, the 'init' parameter was removed and all sub-parameters were brought out one level. the "buildix" parameter, originally meant to cover the "buildix" ickdsf command functionality was also removed.
- all the parameter names were considered and names were either changed or kept based on factors including clarity to end-users, existing names in the ickdsf utility and ansible naming conventions. For example, it was considered to rename "verify_existing_volid" to "verify_existing_serial" or "verify_existing_volser" for more clarity on the expected parameter input, however the term "volid" was found to be extensively used in the ickdsf manual and thus the decision was made to keep the existing name.
- the "verify_existing_volid" parameter was changed from a str type expecting the volid to check against to a bool type to match the other "verify_*" parameters which were also bools. A sub-option will be introduced to provide the volid string. the interface and docs should already reflect this change and the code base will very shortly.
- The results dict was sometimes returning items empty (depending on which code path was followed), these items were removed, they now only get added when appropriate rather than when the results dict is initiated.
- parameters such as 'message' was renamed to 'msg' to conform to existing ibm_zos_core naming conventions
- The descriptions in the docs were cleaned up and updated for clarity.
- The examples given in the docs were also updated to reflect these changes
- A return docstring was added, this is one of the portions of the interface i'd expect to change slightly over time.
- Some practices enforced by the module which are more customizable and flexible in the ickdsf tool were discussed and determined to be sufficient for a first iteration of this ansible module, some examples below:
  -  "index" in the ansible module only takes size whereas in ickdsf it can also be specified where it goes (cylinder, track) -- however it is common practice to have it go (0,1) and thus the ansible module puts it there by default. The added functionality can be added in the future if needed.
- "verify_existing_volid" in the ansible module only takes volid, whereas ickdsf accepts owner too, however the owner check isn't widely used and thus for a first iteration, it was determined the volid check is sufficient.
- "vtoc_tracks" does not have a default value, and it does not make sense to define a singular numerical default, instead the docs explains roughly how the appropriate number is identified by ickdsf if not provided by the user.
- "verify_no_data_set" is defaulted to true in the ansible module, and that is a best practice recommended by the DFSMS team, the option to override that setting is built into the module (and ickdsf)
- "sms_managed" was considered to be renamed to "dfsms_managed" but it appears that sms_managed is a widely known and used term that it is clear enough what the intention is.

**Comment by ketankelkar** [comment]
Ran through all the sanity tests against python3.9 and everything is passing after the style changes were made. Ran the following command for sanity testing from the installed collection location: `ansible-test sanity plugins/modules/zos_ickdsf_init.py --python 3.9`

Some pending changes are marked as 'TODO's but I feel comfortable marking this task complete. I expect some changes to the return structure but those won't be surfaced until the development phase, thus it does not make sense to leave this item open pending those unknown changes.

The output_html params will be removed at a later point in time and the docs and interface will be updated accordingly, however it stays in for now because it is a helpful tool in debugging (as the error reporting is developed in the next phase, the need for the html will go away and then it can be removed)
