### ISSUE TITLE
"CEE3501S The module libpython3.9.so was not found

### ISSUE THREAD

**Issue by GerMFHub** [ansible-collections/ibm_zos_core#656]
### Bug description

running ansible playbooks:
TASK [Create a sequential data set] *************************************************************************************************************************************************************************
fatal: [zos_host]: FAILED! => {"changed": false, "module_stderr": "CEE3501S The module libpython3.9.so was not found.\n         From compile unit TOROLABA:./Python/dynload_shlib.c at entry point _PyImport_FindSharedFuncptr at statement 100 at compile unit offset +00000000372BF5A0 at entry offset +0000000000000290 at address 00000000372BF5A0.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 137}

I am using ansible playbooks from: https://github.com/IBM/z_ansible_collections_samples/tree/main/zos_concepts/data_sets/data_set_basics

at z/os I have this set up:

-bash-4.3$ pip3 list                                                             
Package      Version                                                             
------------ -------                                                             
cffi         1.14.6                                                              
cryptography 3.3.2                                                               
ebcdic       1.1.1                                                               
numpy        1.21.2                                                              
pip          23.0.1                                                              
pycparser    2.20                                                                
setuptools   63.2.0                                                              
six          1.16.0                                                              
zoautil-py   1.2.2                                                               
zos-util     1.0.0                                                               
-bash-4.3$ pip3 --version                                                        
pip 23.0.1 from /x/xxxxxx/.local/lib/python3.10/site-packages/pip (python 3.10)  
-bash-4.3$ python --version                                                      
Python 3.10.7                                                                    
-bash-4.3$                     

on ansible tower :
[xxxxx@xxxxxx data_set_basics]$ ansible --version
ansible 2.9.7                                                

core collection is:
name: ibm_zos_core
version: "1.4.0"
managed_requirements:
    -
        name: "IBM Open Enterprise SDK for Python"
        version: ">=3.9.0"
    -
        name: "Z Open Automation Utilities"
        version:
            - "1.1.0"
            - "1.1.1"

is it a bug or I have misconfigured something? 

### Ansible version

```shell
ansible 2.9.7
```

### IBM z/OS Ansible core Version

v1.4.0

### IBM ZOAU version

v1.2.2

### z/OS version

2.3

**Comment by ddimatos** [comment]
@GerMFHub - thank you for opening an issue. 

I suspect this is configuration related, the example you are using has in it `PYTHONPATH` [in the environment variables](https://github.com/IBM/z_ansible_collections_samples/blob/903936dbc518beed3140a9529bcaf3f250a04aaa/zos_concepts/data_sets/data_set_basics/inventories/group_vars/all.yml#L12) and from what you have shown you have done the PIP PYTHON installation for ZOAU (`zoautil-py 1.2.2`) and that is where I think the problem is. 

With ZOAU (as of today- things will change) you can not be using both `PYTHONPATH` and the PIP installation of the python APIs. The preferred and recommended path is to use PIP as you have done, thus all you should have to do is remove the entry (can comment it out) [here](https://github.com/IBM/z_ansible_collections_samples/blob/903936dbc518beed3140a9529bcaf3f250a04aaa/zos_concepts/data_sets/data_set_basics/inventories/group_vars/all.yml#L12).

PYTHONPATH usage requires and additional step that is likely the error, if you are interested in that installation look for "PYTHONPATH environment method" in this [link](https://www.ibm.com/docs/en/zoau/1.1.x?topic=installing-configuring-zoa-utilities). 

I have not found a good way to provide a sample configuration not knowing if users will use PYTHONPATH or the PIP installation, I will think more about this but also the direction come next year is that PYTHONPATH will not be needed also why have not reviewed this. Come march I will need to update all the configurations in that repository and can add some doc about PYTHONPATH and PIP. 

**While I don't think this has anything to do with your current issue**, I do see an unsupported combination of using ibm_zos_core 1.4.0 with ZOAU 1.2.2, as I noted, its not likely related to your current issue but can produce undesirable problems in the future when the modules start to execute because the Python APIs are different in ZOAU 1.2.x. It really just depends on what functions and modules you use from our collection with zoau 1.2.2 and ansible core 1.4.0 that may or may not work for you longer term. If you want to continue to use ZOAU 1.2.2 , the easiest thing is to install ibm_zos_core collection version 1.5.0-beta.1 which came this week and has support for ZOAU 1.2.2.

**Comment by ddimatos** [comment]
I wanted to share our dependencies for 1.5.0-beta.1:
You can find that [doc](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html#reference) or review:

- Supported by [z/OS V2R3](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.3.0/com.ibm.zos.v2r3/en/homepage.html) or later
- Supported by the [z/OS® shell](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.4.0/com.ibm.zos.v2r4.bpxa400/part1.htm)
- Supported by [IBM Open Enterprise SDK for Python](https://www.ibm.com/products/open-enterprise-python-zos) [3.9](https://www.ibm.com/docs/en/python-zos/3.9) - [3.11](https://www.ibm.com/docs/en/python-zos/3.11)
- Supported by IBM [Z Open Automation Utilities 1.2.x](https://www.ibm.com/docs/en/zoau/1.2.x)

Similarly for your version 1.4.0 you can find them [here](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html#id2)

**Comment by GerMFHub** [comment]
thanks for that, removed PYTHONPATH  as you suggested and that did resolved my issue.
