### ISSUE TITLE
[Enabler] [zos_copy] Some of the code is performing decisions in 2 places. 

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#924]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_copy

### Enabler description

In the zos_copy code there is a method [here](https://github.com/ansible-collections/ibm_zos_core/blob/d5b949e71eb5830cc9664d7c840cfc1b06f7b8f4/plugins/modules/zos_copy.py#L1573):
```
def get_data_set_attributes(
    name,
    size,
    is_binary,
    record_format="VB",
    record_length=1028,
    type="SEQ",
    volume=None
):
```

In this method there is some logic that performs decisions for binary files:
```
    # Overwriting record_format and record_length when the data set has binary data.
    if is_binary:
        record_format = "FB"
        record_length = 80

```
Yet in [other parts of the code decisions are made about binary files](https://github.com/ansible-collections/ibm_zos_core/blob/d5b949e71eb5830cc9664d7c840cfc1b06f7b8f4/plugins/modules/zos_copy.py#L2054) as well and passed to the `get_data_set_attributes`:
```
                if not is_binary:
                    record_format = "FB"
                    record_length = get_file_record_length(src)
```

Although there is nothing wrong with this, it makes following the code a bit more difficult, I think we could remove the logic about binary and other types from within `get_data_set_attributes` and rely on those values be determined before call the function.

**Comment by richp405** [comment]
We have 2 other developers who will be doing work on this module, so this should be re-reviewed after that work is done

**Comment by ketankelkar** [comment]
Recreate playbook using build off of `ibm_zos_core` dev branch ie pre-1.8.0-beta.1
```yml
- hosts : zvm
  collections :
    - ibm.ibm_zos_core
  gather_facts: no

  environment: "{{ environment_vars }}"
  vars:
    test_lib: ANSIBLE.COBOL.TESTLIB

  tasks:
    - name: Delete a data set if it exists
      zos_data_set:
        name: "{{ test_lib }}"
        state: absent

    - name: alloc dest data set with zos_copy
      zos_copy:
        src: "/tmp/HELLOSRC"
        dest: "{{ test_lib }}(MEMAA)"
        executable: yes
        is_binary: yes
        remote_src: yes
```

The data set in question `{{ test_lib }}` should be created with the correct attributes (recf=u, recl=0) and suitable to store loadlibs. 

Instead, the data set is created with recf=FB and recl=80. The above playbook results in module failure with the following:
```
TASK [alloc dest data set with zos_copy] ***********************************************************************************************************
Tuesday 29 August 2023  21:54:59 -0700 (0:00:07.387)       0:00:07.394 ******** 
fatal: [zvm]: FAILED! => {
  "changed": false, 
  "msg": "Unable to copy source /SYSTEM/tmp/HELLOSRC to data set member ANSIBLE.COBOL.TESTLIB(MEMAA)", 
  "rc": 1, 
  "stderr": null,
  "stderr_lines": null,
  "stdout": "cp: FSUMF155 //'ANSIBLE.COBOL.TESTLIB(MEMAA)' must be in undefined record format to store a load module\n", 
  "stdout_lines": null}
```

Removing the `is_binary` from the playbook task results in expected behavior, the `{{ test_lib }}` data set is allocated with the correct attributes (recf=U, recl=0). 

The issue is with the `get_data_set_attributes` function which overrides record_format and record_length attributes when `is_binary=true` is passed in. [src](https://github.com/ansible-collections/ibm_zos_core/blob/9d6704daa5ab73623d63d84a19f906cae01d5db1/plugins/modules/zos_copy.py#L1652C1-L1655C27)
```python
    # Overwriting record_format and record_length when the data set has binary data.
    if is_binary:
        record_format = "FB"
        record_length = 80
```

This override is re-overriding the attributes explicitly set with logic from the `allocate_destination_data_set` method ([src](https://github.com/ansible-collections/ibm_zos_core/blob/9d6704daa5ab73623d63d84a19f906cae01d5db1/plugins/modules/zos_copy.py#L2115C1-L2142C18))
```python
        elif src_ds_type == "USS":
            if os.path.isfile(src):
                # This is almost the same as allocating a sequential dataset.
                size = os.stat(src).st_size
                record_format = record_length = None
                type_ds = "PDSE"

                if is_binary:
                    record_format = "FB"
                    record_length = 80
                else:
                    record_format = "FB"
                    record_length = get_file_record_length(src)

                if executable:
                    record_format = "U"
                    record_length = 0
                    type_ds = "LIBRARY"

                dest_params = get_data_set_attributes(
                    dest,
                    size,
                    is_binary,
                    record_format=record_format,
                    record_length=record_length,
                    type=type_ds,
                    volume=volume
                )
```
