### ISSUE TITLE
[Enabler] [zos_operator] Convert to opercmd's JSON format

### ISSUE THREAD

**Issue by storfibm** [ansible-collections/ibm_zos_core#941]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_operator, zos_operator_action_query

### Enhancement or feature description

ZOAU 1.3 is moving towards broader JSON output generation for its APIs and utilities. The z/OS Core Collection should support this mechanism to allow for more predictable processing, and also minimize chances that changes to the interfaces will break functionality.

**Acceptance Criteria**
Given the z/OS Core Collection
When ZOAU's opercmd functionality is invoked
Then JSON output is processed

**Requirements**
-Refactor zos_operator & zos_operator_action_query as needed
-Invoke ZOAU's new JSON output mechanism for opercmd calls

**Additional context**
https://jsw.ibm.com/browse/NAZARE-9294

**Comment by ddimatos** [comment]
Questions:
1) What is the mechanism for the python APIs, looking. over the source, I saw nothing and no mention of new JSON output, am I to assume a dictionary of the `opercmd.execute(......)` via `vars(....)` or `(...).__dict__` is going to give us the updated JSON response? 
2) Not sure I understand `Retain back-level ZOAU support that runs prior code until all prior ZOAU 1.3 versions are deprecated` , when we raise the minimum version to zoau 1.3 for IBM z/OS Core 1.10.0-beta.1, there will be no backwards compatibility, the APIs differ far to great to maintain backwards compatibility to zoau 1.2.x.

**Comment by storfibm** [comment]
1. You can keep this as waiting on dependency, if the capability did not make it in yet
2. Okay with new hard version boundary
3. Call to me is any invocation of the opercmd capability. Python API or otherwise. No hard requirement to call the shell command directly

**Comment by ddimatos** [comment]
Ansible avoids using shell calls, as stated above. The title implies this ansible would have an interest in a JSON response which aligns to ZOAU shell commands option `-J` over ZOAU python APIs which return a dictionary object named `ZOAUResponse` defined below:
```
"""
    Representation of payload between the Python API and the C or Shell libraries.
    Attributes
    ----------
    rc : int
        Return code of the command executed by the vector.
    stdout_response : str
        Standard out buffer of the executed command.
    stderr_response : str
        Standard error buffer of the executed command.
    command : str
        Full command string, including options and arguments.
    response_format : str
        Encoding label of the payload contents. For example `utf-8`.
    """
```

To date, eg ibm_zos_core version 1.10.0-beta.1 (`dev` branch), the development team did adopt the  ZOAUResponse object for modules:

- zos_operator.py is using the ZOAUResponse
- zos_operator_action_query.py is using the ZOAUResponse
- zos_copy.py is using the ZOAU response but there is a another work item anyhow to remove its usage in zos_copy.

Test framework, conftest.py  `adhoc.all.command(cmd="opercmd '$PJ(*)'")` code continues to use adhoc zoau shell call, this is necessary based on ansibles design, this code is unrelated to product code and exempt from any such requirement. 

Given the current state of the code, JSON is irrelevant here and this issue is being closed. 

See image as well.


![Image](https://github.com/ansible-collections/ibm_zos_core/assets/25803172/6ddf8ba9-399c-454a-9913-1e6519aadcb8)
