### ISSUE TITLE
[Enhancement] Script to check version compatibility of Python on z/OS SDK and  zos open automation utilities

### ISSUE THREAD

**Issue by mjadwani** [ansible-collections/ibm_zos_core#975]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_apf

### Enhancement or feature description

What I am observing at my site is when Python on z/OS is being upgraded it breaks it setup with zos open automation utilities and thus Ansible zos core module breaks and fail in error.
There should be a script to check the compatibility of Python on z/OS and zos automation utilities which can be run post python upgrade or zos open automation utilities upgrade , so one can check whether both available pieces are version compatible and setup correctly so that there is no impact propagated to Ansible zos core modules.

One of the error I recently saw with python when upgraded 3.11 and when zos_apf was executed in a play.

Failed to connect to the host via ssh: CEE3501S The module libpython3.9.so was not found.
         From entry point _PyImport_FindSharedFuncptr at compile unit offset +00000000445C4048 at entry offset +00000000000000F0 at address 00000000445C4048.
fatal: [xxxx.xxx.com]: FAILED! => {
    "changed": false,
    "module_stderr": "CEE3501S The module libpython3.9.so was not found.\n         From entry point _PyImport_FindSharedFuncptr at compile unit offset +00000000445C4048 at entry offset +00000000000000F0 at address 00000000445C4048.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 137
}

**Comment by richp405** [comment]
This is not an issue in ansible core, but on zoau, which we depend on.  Based on the error message, you are using pre-compiled zoau, which was build for python 3.9.  Unfortunatly, the library name it is looking for is hard-coded to the compiled version.  

If you get an error like this, the simple solution is to create a symbolic link.  This needs to be done in the python /lib folder:

symbolic link should be libpython3.9.so, and point to the libpython###.so file that is there.

If your installed file is libpython3.11.so
run the following from that folder
link libpython3.11.so libpython3.9.so

**Comment by ddimatos** [comment]
Thanks @richp405 , I would like to add some more context. 

ZOAU python libraries are compiled with 3.9 which then as noted above are then embedded with `libpython3.11.so` in the source causing this error. While you can create a symlink manually (below) there was a post installation step missed which is to run a `configure.py` script included with ZOAU which manages the linking, those instructions are located [here](https://www.ibm.com/docs/en/zoau/1.2.x?topic=installing-configuring-zoau#pythonpath-environment-method).
```
cd usr/lpp/IBM/cyp/v3r10/pyz/lib
ln libpython3.11.so libpython3.9.so
```

Another way to avoid this is when you not use PYTHONPATH (remove it from the environment variables) and perform  a pip installation of the ZOAU python api's , this will force a compilation and pull in `ibpython3.11.so` to the newly compiled source. 

ZOAU and Ansible teams are investing in this space to simplify installation and use in the near future. 

As for your suggestion to offer a pre-check, at one time we did have such a utility which is [now deprecated](https://github.com/IBM/z_ansible_collections_samples/tree/main/zos_administration/host_setup) because it required extensive maintenance else was prone to errors. We decided to start placing meta data in our collections which will be used in the future for this exact use case. 

Although not written exactly as your use case , issue #894 will be either a playbook, role or even module to aid in support cases such that we can collect valuable data when diagnosing a system. The same issue could address the idea to offer a pre-check which is essentially what we would do with a support case, ensure dependency compatibility. I believe we can track such work with issue #894 thus we can link this issue and close it. 

Thank for reporting this and the suggestion @mjadwan

**Comment by mjadwani** [comment]
@ddimatos  Thankyou for considering the idea . 
I was able to fix the link by running configure.py .

**Comment by ddimatos** [comment]
@mjadwani - while this is an old closed issue, I don't think I responded. We are working towards simplification across a number silo's, we are working with our dependencies (ZOAU, Python, Ansible) as well as in our own code to reduce environment variables and more. 

While still be decided, PIP could possibly be the only option or possibly the recommenced/default for the ZOAU Python modules.
